version: '3.1'
services:
  web:
    container_name: web
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"